const storeProducts = [
    {
        id: 1,
        title: 'Chicken Piccata',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2009/6/11/0/EI1A09_22307_s4x3.jpg.rend.hgtvcom.966.725.suffix/1382538921946.jpeg',
        cookTime: 40,
        category: "chicken",
        servings: 4,
        ingredients: [
            {ing: '2 skinless and boneless chicken breasts, butterflied and then cut in half'},
            {ing: 'Sea salt and freshly ground black pepper'},
            {ing:'All-purpose flour, for dredging'},
            {ing:'6 tablespoons unsalted butter'},
            {ing:'5 tablespoons extra-virgin olive oil'},
            {ing:'1/3 cup fresh lemon juice'},
            {ing:'1/2 cup chicken stock'},
            {ing:'1/4 cup brined capers, rinsed'},
            {ing:'1/3 cup fresh parsley, chopped'}
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Season chicken with salt and pepper. Dredge chicken in flour and shake off excess.'},
            {dir:'2. In a large skillet over medium high heat, melt 2 tablespoons of butter with 3 tablespoons olive oil. When butter and oil start to sizzle, add 2 pieces of chicken and cook for 3 minutes. When chicken is browned, flip and cook other side for 3 minutes. Remove and transfer to plate. Melt 2 more tablespoons butter and add another 2 tablespoons olive oil. When butter and oil start to sizzle, add the other 2 pieces of chicken and brown both sides in same manner. Remove pan from heat and add chicken to the plate.'},
            {dir:'3. Into the pan add the lemon juice, stock and capers. Return to stove and bring to boil, scraping up brown bits from the pan for extra flavor. Check for seasoning. Return all the chicken to the pan and simmer for 5 minutes. Remove chicken to platter. Add remaining 2 tablespoons butter to sauce and whisk vigorously. Pour sauce over chicken and garnish with parsley.'},
        ],
    },
    {
        id: 2,
        title: 'Chicken Salad',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/4/19/1/FN_chicken-salad-030_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371597341383.jpeg',
        cookTime: 30,
        category: "chicken",
        servings: 4,
        ingredients: [
            {ing:'4 cups diced poached chicken'},
            {ing:'1 stalk celery, cut into 1/4-inch dice'},
            {ing:'4 scallions, trimmed and thinly sliced or 1/4 cup sweet onion cut into 1/4-inch dice'},
            {ing:'1 1/2 teaspoons finely chopped fresh tarragon or fresh dill'},
            {ing:'2 tablespoons finely chopped parsley'},
            {ing:'1 cup prepared or homemade mayonnaise'},
            {ing:'2 teaspoons strained freshly squeezed lemon juice'},
            {ing:'1 teaspoon Dijon mustard'},
            {ing:'2 teaspoons kosher salt'},
            {ing:'Freshly ground black pepper'},
        ],
        extraIngredientsStatus: true,
        extraIngredientsTitle: 'POACHED CHICKEN FOR SALADS:',
        extraIngredients: [
            {exIng:'10 sprigs parsley'},
            {exIng:'2 sprigs fresh thyme'},
            {exIng:'1 small onion, halved'},
            {exIng:'1 small carrot, halved'},
            {exIng:'1 stalk celery, halved'},
            {exIng:'3 pounds bone-in, skin-on chicken breasts halves, fat trimmed'},
            {exIng:'5 to 6 cups chicken broth, homemade or low-sodium store bought'},
        ],
        directions: [
            {dir:'1. Toss together the chicken, celery, scallions, dill and parsley in a large bowl.'},
            {dir:'2. In a small bowl, whisk together the mayonnaise, lemon juice, mustard, salt and pepper to taste. Add to the chicken and mix gently until combined. Refrigerate until ready to serve.'},
            {dir:'3. Put the parsley, thyme, onion, carrot, celery, and chicken breasts in a medium saucepan. Cover with the broth, and bring just to a boil. Lower the heat to very low and cover. Poach the chicken until firm to the touch, about 20 minutes. Remove the pan from the heat, uncover and cool the chicken in the liquid for 30 minutes.'},
            {dir:'4. Transfer the chicken to a cutting board and reserve the liquid. Bone and skin the chicken and roughly chop the meat into about 1-inch pieces. Discard the bones and skin.'},
            {dir:'5. Strain the broth and store, covered, in the refrigerator for 3 days or freeze for later use. Remove any fat from the surface of the broth before using.'},
        ],
      },
      {
        id: 3,
        title: 'Chicken Marsala',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2009/4/10/1/FO1D47_24021_s4x3.jpg.rend.hgtvcom.826.620.suffix/1431766598136.jpeg',
        cookTime: 20,
        category: "chicken",
        servings: 4,
        ingredients: [
            {ing:'4 skinless, boneless, chicken breasts (about 1 1/2 pounds)'},
            {ing:'All-purpose flour, for dredging'},
            {ing:'Kosher salt and freshly ground black pepper'},
            {ing:'1/4 cup extra-virgin olive oil'},
            {ing:'4 ounces prosciutto, thinly sliced'},
            {ing:'8 ounces crimini or porcini mushrooms, stemmed and halved'},
            {ing:'1/2 cup sweet Marsala wine'},
            {ing:'1/2 cup chicken stock'},
            {ing:'2 tablespoon unsalted butter'},
            {ing:'1/4 cup chopped flat-leaf parsley'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Put the chicken breasts side by side on a cutting board and lay a piece of plastic wrap over them; pound with a flat meat mallet, until they are about 1/4-inch thick. Put some flour in a shallow platter and season with a fair amount of salt and pepper; mix with a fork to distribute evenly.'},
            {dir:'2. Heat the oil over medium-high flame in a large skillet. When the oil is nice and hot, dredge both sides of the chicken cutlets in the seasoned flour, shaking off the excess. Slip the cutlets into the pan and fry for 5 minutes on each side until golden, turning once – do this in batches if the pieces do not fit comfortably in the pan. Remove the chicken to a large platter in a single layer to keep warm.'},
            {dir:'3. Lower the heat to medium and add the prosciutto to the drippings in the pan, saute for 1 minute to render out some of the fat. Now, add the mushrooms and saute until they are nicely browned and their moisture has evaporated, about 5 minutes; season with salt and pepper. Pour the Marsala in the pan and boil down for a few seconds to cook out the alcohol. Add the chicken stock and simmer for a minute to reduce the sauce slightly. Stir in the butter and return the chicken to the pan; simmer gently for 1 minute to heat the chicken through. Season with salt and pepper and garnish with chopped parsley before serving.'},
        ],
      },
      {
        id: 4,
        title: 'Fried Chicken',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/11/2/0/DV1510H_fried-chicken-recipe-10_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371611618540.jpeg',
        cookTime: 50,
        category: "chicken",
        servings: 8,
        ingredients: [
            {ing:'2 whole free-range, organic chickens'},
            {ing:'Vegetable oil of choice, for frying the chicken'},
            {ing:'6 cups all-purpose flour'},
            {ing:'5 tablespoons salt'},
            {ing:'4 tablespoons ground black pepper'},
            {ing:'2 tablespoons garlic powder'},
            {ing:'1 tablespoon onion powder'},
            {ing:'2 teaspoons cayenne pepper'},
            {ing:'2 cups buttermilk'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Cut the whole chickens into 4 breasts, 4 thighs, 4 legs and 4 wings and set aside.'},
            {dir:'2. Preheat your oil, in either a heavy pan on the stove or a deep-fryer, to 325 degrees F.'},
            {dir:'3. In a large bowl, combine the flour, salt, black pepper, garlic powder, onion powder and cayenne pepper until thoroughly mixed. Set aside.'},
            {dir:'4. Pour the buttermilk into another bowl large enough for the chicken to be immersed in the buttermilk.'},
            {dir:'5. Prepare your dredging station. Place your chicken in a bowl. Next to that, your bowl of buttermilk, and next to that, your dry mixture.'},
            {dir:'6. Take your breasts, lightly dust them with your flour mixture, then dip them in the buttermilk until they are coated, and then place them in the flour mixture.'},
            {dir:'7. Take the breasts that are in the flour mixture and aggressively push the flour mixture into the wet chicken. Make sure that the chicken in very thoroughly coated, or you will not achieve the crust and crunch you are looking for. Gently place the breasts in your hot oil.'},
            {dir:'8. Next, repeat the dredging steps with your other pieces of chicken in this order: thigh, leg then wing.'},
            {dir:'9. When you place the last wing into the fryer, you should have 16 pieces of chicken in the oil. Set a timer for 15 minutes.'},
            {dir:'10. After 15 minutes, take a probe thermometer and check the temperature of a breast. If it reads 180 degrees F, all of your chicken is done. (Keep in mind that it will continue to cook after it has been removed from the fryer.)'},
            {dir:'11. Remove the chicken from the oil and let it drain for 5 minutes. Let cool for an additional 10 minutes before serving.'},
        ],
      },
      {
        id: 5,
        title: 'Perfect Burger',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/3/22/0/FNCC_bobby-flay-perfect-burger-1_s4x3.jpg.rend.hgtvcom.826.620.suffix/1382541341038.jpeg',
        cookTime: 20,
        category: "burger",
        servings: 4,
        ingredients: [
            {ing:'1 1/2 pounds ground chuck (80 percent lean) or ground turkey (90 percent lean)'},
            {ing:'Kosher salt and freshly ground black pepper'},
            {ing:'1 1/2 tablespoons canola oil'},
            {ing:'1/4 cup extra-virgin olive oil'},
            {ing:'4 slices cheese (optional)'},
            {ing:'4 hamburger buns, split; toasted, if desired'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Divide the meat into 4 equal portions (about 6 ounces each). Form each portion loosely into a 3/4-inch-thick burger and make a deep depression in the center with your thumb. Season both sides of each burger with salt and pepper.'},
            {dir:'2. IF USING A GRILL: Heat a gas grill to high or heat coals in a charcoal grill until they glow bright orange and ash over. Brush the burgers with the oil. Grill the burgers until golden brown and slightly charred on the first side, about 3 minutes for beef and 5 minutes for turkey. Flip over the burgers. Cook beef burgers until golden brown and slightly charred on the second side, 4 minutes for medium rare (3 minutes if topping with cheese; see step 3) or until cooked to desired degree of doneness. Cook turkey burgers until cooked throughout, about 5 minutes on the second side.'},
            {dir:'3. IF USING A GRILL PAN: Heat a grill pan over high heat on top of the stove. Cook the burgers as for a grill, above.'},
            {dir:'4. IF USING A SAUTE PAN OR GRIDDLE (PREFERABLY CAST IRON): Heat the oil in the pan or griddle over high heat until the oil begins to shimmer. Cook the burgers until golden brown and slightly charred on the first side, about 3 minutes for beef and 5 minutes for turkey. Flip over the burgers. Cook beef burgers until golden brown and slightly charred on the second side, 4 minutes for medium rare (3 minutes if topping with cheese) or until cooked to desired degree of doneness. Cook turkey burgers until cooked throughout, about 5 minutes on the second side.'},
            {dir:'5. Add the cheese, if using, to the tops of the burgers during the last minute of cooking and top with a basting cover, close the grill cover, or tent the burgers with aluminum foil to melt the cheese.'},
            {dir:'6. Sandwich the hot burgers between the buns and serve immediately.'},
        ],
      },
      {
        id: 6,
        title: 'Turkey Burger',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/3/20/0/0182342_turkey-burger-with-onions_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371603241116.jpeg',
        cookTime: 35,
        category: "burger",
        servings: 4,
        ingredients: [
            {ing:'Extra-virgin olive oil'},
            {ing:'1 onion, cut into 1/4-inch dice'},
            {ing:'Kosher salt'},
            {ing:'2 cloves garlic, smashed and finely chopped '},
            {ing:'1 1/2 pounds ground turkey'},
            {ing:'1/4 cup soy sauce'},
            {ing:'1 tablespoon sambal oelek, optional'},
            {ing:'1-inch piece fresh ginger, peeled and grated'},
            {ing:'One 8-ounce can water chestnuts, drained and coarsely chopped'},
            {ing:'1/2 bunch fresh cilantro leaves, finely chopped'},
        ],
        extraIngredientsStatus: true,
        extraIngredientsTitle: 'Optional Garnishes:',
        extraIngredients: [
            {exIng:'4 slices Cheddar'},
            {exIng:'4 seeded burger buns'},
            {exIng:'1/4 cup mayo mixed with 2 teaspoons sambal oelek'},
            {exIng:'4 slices beefsteak tomatoes'},
            {exIng:'4 slices raw red onion'},
            {exIng:'Butter lettuce'},
        ],
        directions: [
            {dir:'1.Preheat the oven to 200 degrees F to keep the first batch of burgers warm.'},
            {dir:'2. For the burgers: Coat a large saute pan with olive oil. Add the onions, season with salt and bring to a medium-high heat. Cook the onions until they are soft and very aromatic, 7 to 8 minutes. Add the garlic and cook for 1 to 2 minutes. Turn off the heat and let cool.'},
            {dir:'3. In a large mixing bowl, combine the turkey, soy sauce, sambal oelek, ginger, water chestnuts, cilantro and the cooked onions and garlic. (Reserve the onion pan to cook the burgers in later.) Add one-quarter to one-half cup water; this will help the burgers stay nice and moist. Using your hands, squish everything together until they are really well combined.'},
            {dir:'4. Make and cook a little tester patty to be sure that the turkey is really well seasoned. Re-season if needed. If the burger is missing salt add more soy or just give a little sprinkey dink of salt.'},
            {dir:'5. When the burger mix is seasoned appropriately, form the mix into 4 equal size patties.'},
            {dir:'6. Coat the saute pan with new olive oil and bring to a medium-high heat. Place the burgers in the pan. Be sure not to crowd the pan, if you need to work in batches go ahead! Cook the burgers for 5 to 6 minutes on each side. Place the cheese, if using, on the burger and cook for 1 more minute.'},
            {dir:'7. Toast the buns in a broiler or toaster. Schmear each side of the bun lightly with the sambaal mayo. Put a burger on each of the bottom buns and top each burger with tomato, onion and lettuce. Close up each burger, give each one a little squish and them up!'},
        ],
      },
      {
        id: 7,
        title: 'Black Bean Burger',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2015/8/26/2/WU0811H_Black-Bean-Burger_s4x3.jpg.rend.hgtvcom.826.620.suffix/1440693432949.jpeg',
        cookTime: 20,
        category: "burger",
        servings: 1,
        ingredients: [
            {ing: '2 cups black beans, drained and mashed with a fork'},
            {ing: '1 cup seasoned breadcrumbs'},
            {ing: '1/4 cup grated onions'},
            {ing: '1/2 teaspoon chili powder '},
            {ing: '1 egg '},
            {ing: 'Salt and freshly ground black pepper'},
            {ing: 'Canola oil, for oiling grill pan '},
            {ing: '1 to 2 kaiser rolls'},
            {ing: 'Arugula, for serving'},
            {ing: 'Sliced tomatoes, for serving'},
            {ing: 'Mayonnaise, for serving'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Mix together the beans, breadcrumbs, onions, chili powder, egg and some salt and pepper in a medium bowl. Form the mixture into 1 big (or 2 smaller) patties.'},
            {dir:'2. Preheat a grill pan over medium-high heat and add some canola oil. Cook the burger 4 minutes per side. Serve on a kaiser roll with arugula, tomato slices and mayo.'},
        ],
      },
      {
        id: 8,
        title: 'Perfect Salmon Burgers',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/5/4/2/FNM_060111-Perfect-Patties-009_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371597638336.jpeg',
        cookTime: 60,
        category: "burger",
        servings: 4,
        ingredients: [
            {ing: '1 1/4 pounds center-cut salmon fillet, skin and pin bones removed'}, 
            {ing: '2 tablespoons dijon mustard'},
            {ing: '1 tablespoon mayonnaise'}, 
            {ing: '1 tablespoon lemon juice'}, 
            {ing: '1/2 teaspoon grated lemon zest'}, 
            {ing: 'Pinch of cayenne pepper'}, 
            {ing: '2 scallions, chopped'}, 
            {ing: '1 cup plus 2 tablespoons panko (Japanese breadcrumbs)'}, 
            {ing: 'Kosher salt and freshly ground black pepper '}, 
            {ing: '2 tablespoons extra-virgin olive oil, plus more for brushing'}, 
            {ing: '4 brioche buns, split'}, 
            {ing: 'Tartar sauce and arugula, for topping'}, 
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Cut three-quarters of the salmon into 1/4-inch pieces. Put in a large bowl. Cut the rest of the salmon into chunks; transfer the chunks to a food processor along with the mustard, mayonnaise, lemon juice, lemon zest and cayenne. Pulse to make a paste. Add the pureed salmon mixture to the bowl with the diced salmon. Add the scallions, 2 tablespoons panko, 1/2 teaspoon salt, and black pepper to taste. Gently mix until just combined.'},
            {dir:'2. Line a baking sheet with parchment paper and brush with olive oil. Divide the salmon mixture into 4 mounds on the parchment paper. With damp hands, pat into 4-inch-wide, 3/4-inch-thick patties. Cover loosely with plastic wrap and refrigerate at least 30 minutes.'},
            {dir:'3. Preheat the broiler. Spread the remaining 1 cup panko on a plate. Press both sides of the salmon patties in the panko. Heat the olive oil in a large nonstick or cast-iron skillet over medium-high heat. Add the patties (in batches if necessary) and cook until browned on the bottom, 3 to 4 minutes, adjusting the heat if necessary. Turn and cook until the other side is browned and the patties feel springy in the center, 3 to 4 more minutes. Transfer to a paper towel-lined plate to drain; season with salt.'},
            {dir:'4. Meanwhile, arrange the buns, cut-side up, on a broiler pan and broil until toasted, 1 to 2 minutes. Serve the patties on the buns; top with tartar sauce and arugula.'},
        ],
      },
      {
        id: 9,
        title: 'Arugula-Prosciutto Pizza',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/12/7/0/FNM_110111-Prosciutto-Arugula-Pizza-Recipe_s3x4.jpg.rend.hgtvcom.826.620.suffix/1371613739863.jpeg',
        cookTime: 35,
        category: "pizza",
        servings: 4,
        ingredients: [
            {ing: '1 pound prepared pizza dough, at room temperature'},
            {ing: 'All-purpose flour, for dusting'},
            {ing: 'Cornmeal, for dusting'},
            {ing: '4 tablespoons extra-virgin olive oil'},
            {ing: '1 clove garlic, grated'},
            {ing: '1/2 teaspoon chopped fresh rosemary'},
            {ing: 'Kosher salt and freshly ground pepper'},
            {ing: '1/2 cup part-skim ricotta'},
            {ing: '1 cup shredded mozzarella cheese'},
            {ing: '4 cups baby arugula'},
            {ing: '1 small shallot, thinly sliced'},
            {ing: 'Juice of 1/2 lemon'},
            {ing: '3 ounces thinly sliced prosciutto'},
            {ing: 'Shaved parmesan cheese, for topping '},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Place a pizza stone or upside-down baking sheet in the oven and preheat to 450 degrees F. Roll out the dough on a lightly floured surface into a 12-inch round. Transfer to a cornmeal-dusted pizza peel or another upside-down baking sheet; slide the dough onto the hot pizza stone or baking sheet. Bake 8 minutes. Meanwhile, combine 2 tablespoons olive oil in a bowl with the garlic, rosemary, and salt and pepper to taste.'},
            {dir:'2. Remove the pizza from the oven, brush with the olive oil mixture and top with the ricotta and mozzarella. Return the pizza to the oven; bake until the cheese is golden and bubbly, about 6 more minutes.'},
            {dir:'3. Meanwhile, toss the arugula and shallot in a large bowl with the lemon juice, the remaining 2 tablespoons olive oil, and salt and pepper to taste. Top the pizza with the arugula salad, prosciutto and shaved parmesan. Cut into slices.'},
        ],
      },
      {
        id: 10,
        title: 'Barbecue Chicken Pan Pizza',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2019/2/0/TM2830_Barbecue-Chicken-Pan-Pizza.jpg.rend.hgtvcom.826.620.suffix/1552666967920.jpeg',
        cookTime: 30,
        category: "pizza",
        servings: 3,
        ingredients: [
            {ing: '1 rotisserie chicken'},
            {ing: 'EVOO or vegetable oil'},
            {ing: '1 red onion'},
            {ing: '3 to 4 cloves garlic'},
            {ing: 'Salt and pepper'},
            {ing: '1/2 cup chicken stock'},
            {ing: '1 cup ketchup, Sir Kensington preferred brand'},
            {ing: '1/4 cup light brown sugar'},
            {ing: '1/4 cup molasses'},
            {ing: '1/4 cup cider vinegar'},
            {ing: '1/4 cup Worcestershire sauce, Lea and Perrins preferred brand'},
            {ing: '1 tablespoon (scant palm full) smoked sweet paprika'},
            {ing: '1 tablespoon ground mustard'},
            {ing: '1 pound ball dough from market or your favorite pizza parlor or EZ Pizza Dough, recipe follows'},
            {ing: 'AP flour, for dusting'},
            {ing: 'About 1 tablespoon cornmeal'},
            {ing: 'Pinch of crushed red pepper flake'},
            {ing: '1 cup each shredded mozzarella cheese AND shredded yellow cheddar cheese'},
            {ing: 'About 2 tablespoons acacia honey'},
            {ing: '2 tablespoon hot sauce, Franks RedHot or chipotle Tabasco preferred brands'},
            {ing: 'Cilantro leaves'},
            {ing: 'Scallions, sliced'},
            {ing: 'Sliced fresh jalapeno peppers'},
            {ing: 'Garlic Bread Fries, for serving, recipe follows'},
        ],
        extraIngredientsStatus: true,
        extraIngredientsTitle: 'EZ Pizza Dough:',
        extraIngredients: [
            {exIng: '1 cup warm water'},
            {exIng: '1 package active dry yeast (look for pouches marked "For Pizza")'},
            {exIng: '2 tablespoons EVOO, plus some for bowl to rest dough'},
            {exIng: '1 tablespoon acacia honey'},
            {exIng: '2 teaspoons kosher salt'},
            {exIng: '3 cups AP flour'},
        ],
        directions: [
            {dir:'1.Preheat the oven to 525 to 550 degrees F, as high as it goes, with rack at center. Preheat a cast-iron skillet, 12 inches, over medium to medium-high heat (to aid in a crispy bottom crust while pizza is in oven).'},
            {dir:'2. Gather your ingredients.'},
            {dir:'3. Remove skin from chicken, remove meat from bones and pull meat into bite-size pieces. Dice onion, grate or mince garlic.'},
            {dir:'4. Preheat a second cast-iron or other skillet over medium-high heat. Add oil, 2 turns of the pan, then add onions and garlic, season with salt and pepper and soften a few minutes. Add stock and let it finish cooking the onions by absorbing into them. Add ketchup, sugar, molasses, vinegar, Worcestershire, paprika and mustard. Add chicken to sauce, turn in sauce and remove from heat.'},
            {dir:'5. Roll and stretch dough on lightly floured surface into 12 to 14-inch even round that will cover pan. Turn off heat under skillet, sprinkle a little cornmeal in skillet and press dough into hot skillet and up sides as much as possible. The pan is hot -- reminder. Brush the dough with EVOO and season with a little salt and pepper or red pepper flakes. Top the dough with chicken and sauce and top with the cheeses. Place in oven. Bake the pizza 10 to 12 minutes to deep golden brown and bubbly.'},
            {dir:'6. Combine honey, splash of water and hot sauce in small pot or skillet and heat over low heat.'},
            {dir:'7. Drizzle or brush the pizza with the honey mixture and top and scallions, cilantro and jalapeno.'},
            {dir:'1. Ez Pizze Dough: To a mixer with dough hook attached, add warm water and yeast and let the yeast bloom and foam, 5 minutes.'},
            {dir:'1. Add EVOO, honey and salt and turn on mixer. Add the flour gradually to form dough. Transfer to a bowl drizzled with a little EVOO and cover; let stand 1 hour.'},
            {dir:'1. Cut dough in half, wrap half the dough and freeze for later use.'},
        ],
      },
      {
        id: 11,
        title: 'Cast-Iron Pizza',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/9/11/WU2001_Cast-Iron-Pizza_s4x3.jpg.rend.hgtvcom.826.620.suffix/1536690646007.jpeg',
        cookTime: 30,
        category: "pizza",
        servings: 4,
        ingredients: [
            {ing: '1 pound frozen store-bought pizza dough, thawed and risen'},
            {ing: '1/4 cup olive oil'},
            {ing: '1/2 cup store-bought pizza sauce'},
            {ing: '1/2 cup pepperoni'},
            {ing: '4 ounces fresh mozzarella pearls'},
            {ing: '1/4 cup torn fresh basil'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Place a 12-inch cast-iron skillet in the oven and preheat to 500 degrees F.'},
            {dir:'2. Meanwhile, roll or stretch the dough into a 14-inch circle. Carefully remove the skillet from the oven. Drizzle two thirds of the olive oil into the skillet, then carefully transfer the dough to the skillet, pressing the dough up the edges. Spread the sauce over the dough, making sure to get all the way to the edges. Shingle the pepperoni over the sauce and top with the mozzarella pearls. Brush the exposed dough with the remaining olive oil. Bake on the bottom rack until golden brown, 12 to 14 minutes.'},
            {dir:'3. Transfer to a cutting board, top with torn basil, cut into slices and serve.'},
        ],
      },
      {
        id: 12,
        title: 'White Pizza',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2006/5/15/0/tm1314_White_pizza_3.jpg.rend.hgtvcom.826.620.suffix/1371584154107.jpeg',
        cookTime: 30,
        category: "pizza",
        servings: 4,
        ingredients: [
            {ing: '1 store bought pizza dough - or pick one up from your favorite pizzeria'},
            {ing: 'Extra- virgin olive oil, for drizzling'},
            {ing: '2 cups whole or part skim ricotta'},
            {ing: '2 cloves garlic, finely chopped'},
            {ing: 'Handful flat-leaf parsley, finely chopped'},
            {ing: '2 cups shredded mozzarella or provolone, 1 pouch'},
            {ing: '10 fresh basil leaves, 1/2 cup, shredded'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Preheat a pizza stone if you use one along with the oven to 425 degrees F.'},
            {dir:'2. Stretch dough to form a pie and transfer to stone or pizza baking tray. Pierce the dough with the tines of a fork in several places. Drizzle extra-virgin olive oil around the crust. Mix the ricotta cheese with garlic and parsley and season it with salt and black pepper. Spread the ricotta across the dough. Top the pizza with mozzarella or provolone. Bake until crispy, 20 minutes. Top the white pizza pie with the shredded basil leaves, cut and serve.'},
        ],
      },
      {
        id: 13,
        title: 'Sirloin Steak',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/7/26/1/EA1G10_skirt-steak_s4x3.jpg.rend.hgtvcom.826.620.suffix/1430426675052.jpeg',
        cookTime: 23,
        category: "steak",
        servings: 4,
        ingredients: [
            {ing: '1 1/2 pounds sirloin steak, 1 to 1 1/4-inches thick'},
            {ing: '2 teaspoons olive oil'},
            {ing: 'Salt and freshly ground black pepper'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Preheat oven on broiler setting. Make foil "snake" out of aluminum foil to use to keep oven door slightly ajar so that broiler does not turn off if it gets too hot. Brush steak with oil and salt and pepper, to taste. Place a piece of foil on the bottom rack as a drip pan. Place another rack in the position above this and put the steak directly on this rack. '},
            {dir:'2. Cook steak in this position for 5 minutes. Flip steak and cook for another 5 minutes. Move rack with steak to top position in oven, moving rack with foil and drippings just underneath, and cook for 3 minutes. Flip 1 last time and cook for another 3 minutes. Transfer steak to wire rack and rest for 3 to 5 minutes. The above times are for medium doneness. Adjust cooking times up or down as desired.'},
        ],
      },
      {
        id: 14,
        title: 'Grilled Tuna Steaks',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/8/1/0/BX0404H_Grilled-Tuna-Steaks_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371607062643.jpeg',
        cookTime: 16,
        category: "steak",
        servings: 4,
        ingredients: [
            {ing: 'Four 1-inch-thick fresh tuna steaks (about 4 pounds)'},
            {ing: 'Olive oil'},
            {ing: 'Kosher salt and freshly ground black pepper'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1.'},
        ],
      },
      {
        id: 15,
        title: 'Swiss Steak',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/8/1/0/BX0404H_Grilled-Tuna-Steaks_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371607062643.jpeg',
        cookTime: 200,
        category: "steak",
        servings: 5,
        ingredients: [
            {ing: '2 pounds beef bottom round, trimmed of excess fat'},
            {ing: '2 teaspoons kosher salt'},
            {ing: '1 teaspoon freshly ground black pepper'},
            {ing: '3/4 cup all-purpose flour'},
            {ing: '1/4 cup vegetable oil or bacon drippings'},
            {ing: '1 large onion, thinly sliced'},
            {ing: '2 cloves garlic, minced'},
            {ing: '2 stalks celery, chopped'},
            {ing: '1 tablespoon tomato paste'},
            {ing: '1 (14.5-ounce) can diced tomatoes'},
            {ing: '1 teaspoon smoked paprika'},
            {ing: '1 teaspoon dried oregano'},
            {ing: '1 tablespoon Worcestershire sauce'},
            {ing: '1 1/2 cups beef broth'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Preheat the oven to 325 degrees F.'},
            {dir:'2. Cut the meat with the grain into 1/2-inch thick slices and season on both sides with the salt and pepper. Place the flour into a pie pan. Dredge the pieces of meat on both sides in the flour mixture. Tenderize the meat using a needling device, until each slice is 1/4-inch thick. Dredge the slices on both sides once more and set aside.'},
            {dir:'3. Add enough of the bacon drippings or vegetable oil to just cover the bottom of a 4 to 5-quart Dutch oven set over medium-high heat. Once the oil begins to shimmer, add the steaks to the pan, being careful not to overcrowd. Cook until golden brown on both sides, approximately 2 minutes per side. Remove the steaks to a plate and repeat until all of the steaks have been browned.'},
            {dir:'4. Remove the last steaks from the pot and add the onions, garlic, and celery. Saute for 1 to 2 minutes. Add the tomato paste and stir to combine. Next add the tomatoes, paprika, oregano, Worcestershire sauce and beef broth and stir to combine. Return the meat to the pot, submerging it in the liquid. Cover the pot and place it in the oven on the middle rack. Cook for 1 1/2 to 2 hours or until the meat is tender and falling apart.'},
        ],
      },
      {
        id: 16,
        title: 'Steak Bites',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/4/27/0/WU0209H_steak-bites_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371606042811.jpeg',
        cookTime: 25,
        category: "steak",
        servings: 2,
        ingredients: [
            {ing: '1 pound sirloin steak (without much gristle) or pre-cut beef tips'},
            {ing: 'Kosher salt and fresh ground black pepper'},
            {ing: 'Kosher salt and fresh ground black pepper'},
            {ing: 'Butter'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Trim off the excess fat from the meat, and then cut strips less than 1-inch wide. Rotate the meat and cut into small bite-size pieces. If you see any more large chunks of fat, gristle or long silvery membrane, cut them off.'},
            {dir:'2. Sprinkle generously with kosher salt and freshly ground pepper. Toss the meat around a bit to thoroughly coat with the seasonings.'},
            {dir:'3. Next, turn on your ventilation fan-you will need it! Heat the skillet over medium-high to high heat. As the pan heats, add about 2 tablespoons butter to the skillet. Allow the butter to melt, and then get very brown, before you add the meat.'},
            {dir:'4. Place some of the meat in the pan in a single layer. It should sizzle loudly when it hits the pan - if it does nott, the pan is not hot enough. Don not stir or disrupt the meat for 30 to 45 seconds. You want it to sizzle and brown on one side. Scoop as many steak bites as you can with your spatula and flip them over. Repeat until all the meat is turned. Cook for an additional 30 to 45 seconds-just long enough to sear the outside of the meat but NOT cook the inside.'},
            {dir:'5. Remove the meat to a clean plate. Add a little more butter to the pan and repeat the cooking process with the next batch just as before. Lastly, when all the meat is nicely browned and removed to the plate, pour all that browned/blackened butter all over the meat. And enjoy!'},
        ],
      },
      {
        id: 17,
        title: 'Sushi Rice',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2009/6/5/0/FO1A14_11563_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371589348725.jpeg',
        cookTime: 30,
        category: "sushi",
        servings: 4,
        ingredients: [
            {ing: '3 cups short-grain white rice'},
            {ing: '1/4 cup rice wine vinegar'},
            {ing: '1/4 cup sugar'},
            {ing: '1 teaspoon salt'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Before cooking the rice, rinse several times in running water until the water runs clear. Drain in a colander for about 1 hour. Cook on the stovetop or in an electric rice cooker according to package directions.'},
            {dir:'2. In a small saucepan over low heat, combine vinegar, sugar and salt. Stir gently to dissolve salt and sugar. Cool to room temperature.'},
            {dir:'3. While the rice is still warm, transfer to a large non-reactive bowl. Gradually drizzle the vinegar mixture over the rice, fanning the rice as you go. Use a rice paddle to mix gently without mashing the grains. Keep the rice covered with a damp cloth at room temperature until ready to make sushi. Do not refrigerate.'},
        ],
      },
      {
        id: 18,
        title: 'Prairie Sushi',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2014/5/20/0/WU0303H_Prairie-Sushi_s4x3.jpg.rend.hgtvcom.826.620.suffix/1400740916429.jpeg',
        cookTime: 75,
        category: "sushi",
        servings: 6,
        ingredients: [
            {ing: 'One 8-ounce package cream cheese'},
            {ing: '1 tablespoon fresh chopped basil'},
            {ing: '1 teaspoon fresh minced chives'},
            {ing: '1 tablespoon fresh chopped parsley'},
            {ing: '1 tablespoon lemon juice'},
            {ing: 'Salt and freshly ground black pepper'},
            {ing: '6 taco-sized flour tortillas'},
            {ing: '1 pound thinly shaved turkey'},
            {ing: '3 carrots, julienned'},
            {ing: '1 cucumber, julienned'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Mix the cream cheese, basil, chives, parsley, lemon juice, and sprinkle with salt and pepper together in a bowl.'},
            {dir:'2. Lay out the tortillas and spread with the herb cream cheese mixture. Next, layer on the turkey, carrots and cucumber onto each tortilla. Like making sushi, roll the tortillas up tightly, then wrap in plastic wrap and refrigerate, about 1 hour. When ready to serve, unwrap the sushi rolls and slice into quarters.'},
        ],
      },
      {
        id: 19,
        title: 'Nigiri Sushi',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/10/27/0/ad1a10_sushi.jpg.rend.hgtvcom.826.620.suffix/1371583036385.jpeg',
        cookTime: 100,
        category: "sushi",
        servings: 6,
        ingredients: [
            {ing: '3 1/3 cup short-grain sushi rice, rinsed'},
            {ing: '4 cups water'},
            {ing: '5 1/3 tablespoons sushi vinegar, or 5 1/3 tablespoons rice vinegar, 5 tablespoons sugar and 3 tablespoons'},
            {ing: 'Salt'},
            {ing: '1 (4 to 6 ounce) piece sushi-grade tuna or salmon'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Wash the rice until the water rinses clear. Drain the rice in a colander and let it stand for 30 minutes. Place the rice in a pot or rice cooker, and add 4 cups of water or follow the instructions on a rice cooker. Bring the water to a boil. Reduce the heat to a simmer and cover the pot. Cook for 15 minutes. Remove the cover, place a damp towel over the rice, and let cool for 10 minutes.'},
            {dir:'2. You can find sushi vinegar prepared at a grocery story or you can easily make it by pouring the vinegar, sugar and salt into a pan under low heat until the sugar and salt are dissolved. If you like sweeter vinegar, add more sugar.'},
            {dir:'3. Pour sushi vinegar over cooked rice and mix it gently. You can do this in a wooden bowl for making sushi rice or in your rice cooker by turning off the cooker and pouring the vinegar and mixing gently and evenly and leaving it until it cools down to room temperature. The lid should remain open.'},
            {dir:'4. Buy fresh fish at a fish market or a Japanese grocery store, make sure to ask the clerk if the fish is good for eating raw. Only purchase sushi-grade fish. With salmon, be sure to cover fish with salt and leave for 1 hour. Then, rinse off salt and put it into the freezer. Once frozen, defrost and use for sushi. Slice the fish very thinly into bite-sized pieces.'},
            {dir:'5. Hand-mold fingers of rice and place a thin slices of fish on the top..'},
        ],
      },
      {
        id: 20,
        title: 'Sushi Cake',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/2/7/0/FNM_030118-Piece-of-Cake-Sushi_s4x3.jpg.rend.hgtvcom.826.620.suffix/1518021937256.jpeg',
        cookTime: 150,
        category: "sushi",
        servings: 10,
        ingredients: [
            {ing: 'Cooking spray'},
            {ing: '1 15- to 16-ounce box yellow cake mix (plus required ingredients)'},
            {ing: '1 16-ounce tub white frosting'},
            {ing: '1 cup bright white candy melts'},
            {ing: '3/4 cup puffed rice cereal'},
            {ing: '4 to 5 pieces dried mango or papaya'},
            {ing: '1/2 green apple, cut into small pieces'},
            {ing: 'Juice of 1/2 lemon'},
            {ing: '1 10-ounce bag mini marshmallows'},
            {ing: '1 1-pound box confectioners sugar'},            
            {ing: '1 1/4 cups dark cocoa powder, plus more for dusting'},
            {ing: '4 tablespoons unsalted butter, at room temperature'},
            {ing: 'Green food coloring'},
            {ing: '4 to 5 pink Starburst candies'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Preheat the oven to 350 degrees F. Coat two 8-inch round cake pans with cooking spray. Prepare the cake mix as directed; divide the batter between the pans and bake as directed. Let cool 15 minutes, then remove to a rack to cool completely.'},
            {dir:'2. Trim the domed tops of the cakes with a long serrated knife to make them level. Spread frosting on one cake layer, then invert the other layer on top. Spread a thin layer of frosting around the outside of the cake and on top. Reserve 1/4 cup frosting for the wasabi.'},
            {dir:'3. Melt the candy melts in the microwave, stirring every 30 seconds, until smooth. Add the cereal and stir.'},
            {dir:'4. Mark a 3 1/2-inch circle in the middle of the cake with a paring knife. Arrange the dried mango in half of the circle, trimming as needed. Toss the apple with the lemon juice and arrange cut-side up next to the dried mango, pushing it into the cake.'},
            {dir:'5. Wrap a 5-by-26-inch strip of parchment around the cake so that it is slightly taller than the cake. Spread the cereal mixture around the apple and dried mango (the parchment will create a wall for the cereal mixture). Refrigerate the cake.'},
            {dir:'6. To make the seaweed, microwave the marshmallows and 1/4 cup water in a bowl in 30-second intervals, stirring, until smooth. Transfer to a stand mixer. Beat in the confectioners sugar with the paddle attachment, then gradually beat in the cocoa powder until smooth. Beat in the butter.'},
            {dir:'7. Dust a piece of parchment with cocoa powder and roll the chocolate mixture into a 5-by-26-inch strip. Trim the long sides to make them straight.'},
            {dir:'8. Remove the parchment from the cake. Carefully wrap the chocolate strip around the cake, making sure the top of the strip aligns with the top of the cereal mixture. Trim the bottom edge so its flush with the bottom of the cake. If the strip tears, just press it back together. Transfer the cake to a board.'},
            {dir:'9. For the wasabi, tint the reserved frosting with green food coloring and freeze until stiff, 15 minutes; scoop onto the board. For the pickled ginger, flatten the Starburst candies, shape into curvy pieces and place on the board.'},
        ],
      },
      {
        id: 21,
        title: 'Grilled Seafood Salad',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/18/0/ei1b04_grilled_seafood_salad.jpg.rend.hgtvcom.826.620.suffix/1529011556835.jpeg',
        cookTime: 30,
        category: "seafood",
        servings: 4,
        ingredients: [
            {ing: '1/2 cup olive oil'},
            {ing: '2 garlic cloves, coarsely chopped'},
            {ing: '1 tablespoon chopped fresh Italian parsley leaves'},
            {ing: '1 teaspoon chopped fresh marjoram leaves'},
            {ing: '1 teaspoon chopped fresh thyme leaves'},
            {ing: '1/4 cup fresh lemon juice'},
            {ing: 'Salt and freshly ground black pepper'},
            {ing: '12 ounces sea scallops'},
            {ing: '12 ounces squid, bodies only'},
            {ing: '3 ounces arugula leaves (about 6 cups)'},
            {ing: '2 carrots, peeled, cut into thin strips'},
            {ing: '1/2 yellow bell pepper, cut into thin strips'},
            {ing: '1 (15-ounce) can white beans (cannellini), drained, rinsed'},
            {ing: '1 large head radicchio, leaves separated'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Heat the oil in a heavy medium skillet over medium-low heat. Add the garlic, let it cook for 1 to 2 minutes and then add the herbs and saute until fragrant, about 30 seconds. Cool to room temperature. Whisk in the lemon juice. Season the dressing with salt and pepper, to taste.'},
            {dir:'2. Prepare the barbecue (medium-high heat). Pat the scallops and squid dry with paper towels and thread them onto skewers. Brush them with 2 tablespoons of the dressing. Sprinkle with salt and pepper. Grill the scallops and squid until just cooked through, turning once, 2 to 3 minutes per side. Cool completely. Cut the squid crosswise into 1/4-inch-wide rings.'},
            {dir:'3. Combine the arugula, carrots, bell peppers, and cannellini beans in a large bowl. Toss with 1/2 cup of the dressing to coat.'},
            {dir:'4. Place 1 large or 2 medium radicchio leaves on each of 4 plates. Spoon the bean salad into the radicchio cups. Top with the scallops and squid. Drizzle the remaining dressing over the seafood and serve.'},
        ],
      },
      {
        id: 22,
        title: 'Seafood Paella',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2017/8/15/0/CCTIA0301_Seafood-Paella_s4x3.jpg.rend.hgtvcom.826.620.suffix/1502826649304.jpeg',
        cookTime: 100,
        category: "seafood",
        servings: 10,
        ingredients: [
            {ing: '1/2 teaspoon saffron threads'},
            {ing: '1 tablespoon lemon juice'},
            {ing: '1 pound large shrimp (21/25 count), peeled and deveined, tail on'},
            {ing: '2 teaspoons smoked paprika'},
            {ing: 'Kosher salt and freshly ground black pepper'}, 
            {ing: '1/4 cup olive oil'},
            {ing: '3 roasted red peppers, cut into small dice'},
            {ing: '1 yellow onion, cut into small dice'}, 
            {ing: '1/2 cup chopped fresh parsley'},
            {ing: '1 bay leaf'},
            {ing: '4 cloves garlic, minced'}, 
            {ing: '1 teaspoon cumin'},
            {ing: '3 cups paella rice'}, 
            {ing: '1 cup dry white wine'}, 
            {ing: 'One 28-ounce can diced tomatoes'}, 
            {ing: '4 cups chicken stock, warm'}, 
            {ing: '12 littleneck clams, scrubbed'}, 
            {ing: '12 mussels, cleaned'}, 
            {ing: '3 lobster tails, halved lengthwise'},
            {ing: '1/2 cup frozen sweet peas, thawed'}, 
            {ing: 'Lemon wedges, for serving'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Preheat the oven to 400 degrees F.'},
            {dir:'2. Combine the saffron and lemon juice in a small bowl and crush the threads with the back of a spoon until the mixture turns bright yellow. Let sit for 5 minutes.'},
            {dir:'3. Toss the shrimp with 1 teaspoon of the smoked paprika, 1 teaspoon salt and 1/2 teaspoon pepper. Set aside.'},
            {dir:'4. Heat the olive oil in a Dutch oven over medium-high heat. When hot, add the roasted peppers, onion, parsley and bay leaf. Saute until the onion is translucent, 5 to 8 minutes. Add the garlic, cumin and the remaining 1 teaspoon smoked paprika; saute until fragrant, 30 seconds. Add the rice and toast until slightly browned, 2 to 3 minutes.'},
            {dir:'5. Pour in the wine, scrapping up any browned bits from the bottom of the pan. Cook, stirring, until the wine is fully absorbed. Pour in the tomatoes, stock, saffron mixture, 1 teaspoon salt and 1/2 teaspoon pepper; stir until combined. Bring to a simmer, then nestle the clams into the rice. Cover and let simmer for 5 minutes. Add the mussels, shrimp and lobster. Cover and transfer to the oven for 25 to 30 minutes, until the clams and mussels are opened.'},
            {dir:'6. Place the pot back on the stovetop over medium-high heat. Add the peas. Cook until the bottom of the rice forms a crust, about 5 minutes. Serve the paella with lemon wedges.'},
        ],
      },
      {
        id: 23,
        title: 'Seafood Salad',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/12/5/0/FNM_010112-WN-Dinners-038_s4x3.jpg.rend.hgtvcom.826.620.suffix/1382541015485.jpeg',
        cookTime: 35,
        category: "seafood",
        servings: 4,
        ingredients: [
            {ing: '3 stalks celery (1 quartered, 2 thinly sliced)'},
            {ing: '3 small cloves garlic (2 smashed, 1 chopped)'},
            {ing: 'Juice of 1 lemon'},
            {ing: 'Kosher salt and freshly ground pepper'},
            {ing: '8 ounces baby carrots, halved lengthwise'},
            {ing: '3/4 pound small shrimp, peeled and deveined'},
            {ing: '1/2 pound sea scallops, halved horizontally'},
            {ing: '1 small avocado, halved, pitted and peeled'},
            {ing: '2 romaine lettuce hearts, torn'},
            {ing: '1 tablespoon capers, plus 1 tablespoon brine from the jar'},
            {ing: '2 cups croutons'},
            {ing: '1 tablespoon light mayonnaise'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Combine the quartered celery, smashed garlic, half of the lemon juice, 10 cups water, and salt and pepper to taste in a large saucepan. Cover and bring to a boil, then uncover, add the carrots and cook 2 minutes. Add the shrimp and cook until opaque, about 4 minutes. With a slotted spoon, transfer the carrots and shrimp to a colander and rinse under cold water. Return the water to a boil, add the scallops and cook until opaque, 1 to 2 minutes. Remove the scallops with a slotted spoon, add to the colander and rinse under cold water.'},
            {dir:'2. Ladle out 1/3 cup of the poaching liquid; set aside to cool. Dice half of the avocado and combine with the sliced celery, lettuce, capers and croutons in a large bowl. Add the carrots, shrimp and scallops.'},
            {dir:'3. Puree the remaining avocado half in a blender with the reserved poaching liquid, the remaining lemon juice, the caper brine, chopped garlic, mayonnaise, 1/2 teaspoon salt, and pepper to taste. Toss with the salad and season with salt and pepper.'},
        ],
      },
      {
        id: 24,
        title: 'Seafood Gumbo',
        img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2012/9/4/3/FNM_100112-Seafood-Gumbo-Recipe_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371609297629.jpeg',
        cookTime: 300,
        category: "seafood",
        servings: 12,
        ingredients: [
            {ing: '1 cup all-purpose flour'},
            {ing: '1 cup vegetable oil'},
            {ing: '2 cups finely chopped onion'},
            {ing: '2 green bell peppers, finely chopped'},
            {ing: '1 blue crab'},
            {ing: '1 lobster tail'},
            {ing: "1/4 cup Creole seasoning (preferably Tony Chachere's)"},
            {ing: '4 pounds medium shrimp, peeled and deveined'},
            {ing: '1 pound crabmeat'},
            {ing: '1 bunch scallions, finely chopped'},
            {ing: '1/2 bunch parsley, finely chopped'},
            {ing: 'Cooked white rice, for serving (optional)'},
        ],
        extraIngredientsStatus: false,
        directions: [
            {dir:'1. Make the roux: Combine the flour and vegetable oil in a wide Dutch oven over medium-low heat and cook, whisking constantly, until dark brown, about 45 minutes. Remove from the heat and set aside.'},
            {dir:'2. Bring 10 quarts water to a boil in an extra-large, wide pot. Stir in the onion, bell peppers and roux and cook over medium heat, stirring occasionally, until the vegetables are very soft, about 45 minutes. Add the blue crab and lobster tail and boil until cooked through, 15 to 20 minutes. Remove the lobster tail and crab; discard the crab. Let the lobster cool slightly, then remove the meat from the shell and cut into small chunks; refrigerate until ready to use.'},
            {dir:'3. Add the Creole seasoning to the pot and bring to a boil; cook until the liquid reduces by one-quarter, about 1 hour, 30 minutes. Add the shrimp and cook over medium heat until firm, about 20 minutes. Add the crabmeat and reserved lobster meat and cook 10 minutes. Stir in the scallions and parsley and remove from the heat. Cover and let stand 30 minutes. Serve over rice.'},
        ],
      },
  ];
  
export default storeProducts;
  